title: "Extreme Environment Seismology Laboratory"
description: "大阪教育大学｜極限環境地震学研究室"
logo: "/images/logo_trans.png" 
url: "https://nishikawa-lab.jp"
baseurl: ""
future: true
markdown: kramdown
theme: minima   # 何かテーマを使ってる前提
plugins:
  - jekyll-feed
kramdown:
  toc_levels: 1..6
  auto_ids: false
